PACKAGE_NAME="quicktake-keyspan"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="keyspan"
DEST_MODULE_LOCATION[0]="/kernel/drivers/usb/serial"
AUTOINSTALL="yes"
MAKE[0]="make -C /usr/lib/modules/$kernelver/build M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build modules"
CLEAN="make -C /usr/lib/modules/$kernelver/build M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build clean"

